/* tslint:disable */
/* eslint-disable */
/**
 * iotbrlabs-api
 * API da iotbrlabs
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: mhd_look@hotmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Clientes,
  ClientesFilter,
  ClientesFilter1,
  ClientesPartial,
  ClientesWithRelations,
  LoopbackCount,
  NewClientes,
} from '../models/index';
import {
    ClientesFromJSON,
    ClientesToJSON,
    ClientesFilterFromJSON,
    ClientesFilterToJSON,
    ClientesFilter1FromJSON,
    ClientesFilter1ToJSON,
    ClientesPartialFromJSON,
    ClientesPartialToJSON,
    ClientesWithRelationsFromJSON,
    ClientesWithRelationsToJSON,
    LoopbackCountFromJSON,
    LoopbackCountToJSON,
    NewClientesFromJSON,
    NewClientesToJSON,
} from '../models/index';

export interface IotbrlabsCtrlControllerCountRequest {
    where?: { [key: string]: any; };
}

export interface IotbrlabsCtrlControllerCreateRequest {
    newClientes?: NewClientes;
}

export interface IotbrlabsCtrlControllerDeleteByIdRequest {
    id: number;
}

export interface IotbrlabsCtrlControllerFindRequest {
    filter?: ClientesFilter1;
}

export interface IotbrlabsCtrlControllerFindByIdRequest {
    id: number;
    filter?: ClientesFilter;
}

export interface IotbrlabsCtrlControllerReplaceByIdRequest {
    id: number;
    clientes?: Omit<Clientes, 'id'>;
}

export interface IotbrlabsCtrlControllerUpdateAllRequest {
    where?: { [key: string]: any; };
    clientesPartial?: Omit<ClientesPartial, 'id'>;
}

export interface IotbrlabsCtrlControllerUpdateByIdRequest {
    id: number;
    clientesPartial?: Omit<ClientesPartial, 'id'>;
}

/**
 * 
 */
export class IotbrlabsCtrlControllerApi extends runtime.BaseAPI {

    /**
     */
    async iotbrlabsCtrlControllerCountRaw(requestParameters: IotbrlabsCtrlControllerCountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoopbackCount>> {
        const queryParameters: any = {};

        if (requestParameters['where'] != null) {
            queryParameters['where'] = requestParameters['where'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/clientes/count`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LoopbackCountFromJSON(jsonValue));
    }

    /**
     */
    async iotbrlabsCtrlControllerCount(requestParameters: IotbrlabsCtrlControllerCountRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoopbackCount> {
        const response = await this.iotbrlabsCtrlControllerCountRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async iotbrlabsCtrlControllerCreateRaw(requestParameters: IotbrlabsCtrlControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Clientes>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/clientes`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NewClientesToJSON(requestParameters['newClientes']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClientesFromJSON(jsonValue));
    }

    /**
     */
    async iotbrlabsCtrlControllerCreate(requestParameters: IotbrlabsCtrlControllerCreateRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Clientes> {
        const response = await this.iotbrlabsCtrlControllerCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async iotbrlabsCtrlControllerDeleteByIdRaw(requestParameters: IotbrlabsCtrlControllerDeleteByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling iotbrlabsCtrlControllerDeleteById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/clientes/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async iotbrlabsCtrlControllerDeleteById(requestParameters: IotbrlabsCtrlControllerDeleteByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.iotbrlabsCtrlControllerDeleteByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async iotbrlabsCtrlControllerFindRaw(requestParameters: IotbrlabsCtrlControllerFindRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ClientesWithRelations>>> {
        const queryParameters: any = {};

        if (requestParameters['filter'] != null) {
            queryParameters['filter'] = requestParameters['filter'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/clientes`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ClientesWithRelationsFromJSON));
    }

    /**
     */
    async iotbrlabsCtrlControllerFind(requestParameters: IotbrlabsCtrlControllerFindRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ClientesWithRelations>> {
        const response = await this.iotbrlabsCtrlControllerFindRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async iotbrlabsCtrlControllerFindByIdRaw(requestParameters: IotbrlabsCtrlControllerFindByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClientesWithRelations>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling iotbrlabsCtrlControllerFindById().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['filter'] != null) {
            queryParameters['filter'] = requestParameters['filter'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/clientes/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClientesWithRelationsFromJSON(jsonValue));
    }

    /**
     */
    async iotbrlabsCtrlControllerFindById(requestParameters: IotbrlabsCtrlControllerFindByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClientesWithRelations> {
        const response = await this.iotbrlabsCtrlControllerFindByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async iotbrlabsCtrlControllerReplaceByIdRaw(requestParameters: IotbrlabsCtrlControllerReplaceByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling iotbrlabsCtrlControllerReplaceById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/clientes/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ClientesToJSON(requestParameters['clientes']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async iotbrlabsCtrlControllerReplaceById(requestParameters: IotbrlabsCtrlControllerReplaceByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.iotbrlabsCtrlControllerReplaceByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async iotbrlabsCtrlControllerUpdateAllRaw(requestParameters: IotbrlabsCtrlControllerUpdateAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoopbackCount>> {
        const queryParameters: any = {};

        if (requestParameters['where'] != null) {
            queryParameters['where'] = requestParameters['where'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/clientes`,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ClientesPartialToJSON(requestParameters['clientesPartial']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LoopbackCountFromJSON(jsonValue));
    }

    /**
     */
    async iotbrlabsCtrlControllerUpdateAll(requestParameters: IotbrlabsCtrlControllerUpdateAllRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoopbackCount> {
        const response = await this.iotbrlabsCtrlControllerUpdateAllRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async iotbrlabsCtrlControllerUpdateByIdRaw(requestParameters: IotbrlabsCtrlControllerUpdateByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling iotbrlabsCtrlControllerUpdateById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/clientes/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ClientesPartialToJSON(requestParameters['clientesPartial']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async iotbrlabsCtrlControllerUpdateById(requestParameters: IotbrlabsCtrlControllerUpdateByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.iotbrlabsCtrlControllerUpdateByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
