// Auto-generated by https://github.com/vladkens/apigen-ts
// Source: https://iotbrlabs-api-874733105499.us-central1.run.app/openapi.json

type Headers = Record<string, string>;
export type ApigenHeaders =
  | Headers
  | ((method: string, path: string) => Headers | Promise<Headers>);

export interface ApigenConfig {
  baseUrl: string;
  headers: ApigenHeaders;
}

export interface ApigenRequest extends Omit<RequestInit, "body"> {
  search?: Record<string, unknown>;
  body?: unknown;
}

export class ApiClient {
  clientesIdPatch(id: string | null, data: any) {
      throw new Error('Method not implemented.');
  }
  clientesGet() {
      throw new Error('Method not implemented.');
  }
  clientesPost(data: any) {
      throw new Error('Method not implemented.');
  }
  clientesIdDelete(id: string | null) {
      throw new Error('Method not implemented.');
  }
  Config: ApigenConfig;

  constructor(config?: Partial<ApigenConfig>) {
    this.Config = { baseUrl: "/", headers: {}, ...config };
  }

  async ParseError(rep: Response) {
    try {
      return await rep.json();
    } catch (e) {
      throw rep;
    }
  }

  PrepareFetchUrl(path: string): URL {
    let base = this.Config.baseUrl;
    if ("location" in globalThis && (base === "" || base.startsWith("/"))) {
      const { location } = globalThis as unknown as {
        location: { origin: string };
      };
      base = `${location.origin}${base.endsWith("/") ? base : `/${base}`}`;
    }

    return new URL(path, base);
  }

  async Fetch<T>(
    method: string,
    path: string,
    opts: ApigenRequest = {},
  ): Promise<T> {
    const url = this.PrepareFetchUrl(path);

    for (const [k, v] of Object.entries(opts?.search ?? {})) {
      url.searchParams.append(
        k,
        Array.isArray(v) ? v.join(",") : (v as string),
      );
    }

    const configHeaders =
      typeof this.Config.headers === "function"
        ? await this.Config.headers(method, path)
        : this.Config.headers;

    const headers = new Headers({ ...configHeaders, ...opts.headers });
    const ct = headers.get("content-type") ?? "application/json";

    let body: FormData | URLSearchParams | string | undefined = undefined;

    if (
      ct === "multipart/form-data" ||
      ct === "application/x-www-form-urlencoded"
    ) {
      headers.delete("content-type");
      body =
        ct === "multipart/form-data" ? new FormData() : new URLSearchParams();
      for (const [k, v] of Object.entries(
        opts.body as Record<string, string>,
      )) {
        body.append(k, v);
      }
    }

    if (ct === "application/json" && typeof opts.body !== "string") {
      headers.set("content-type", "application/json");
      body = JSON.stringify(opts.body);
    }

    const credentials = opts.credentials ?? "include";
    const rep = await fetch(url.toString(), {
      method,
      ...opts,
      headers,
      body,
      credentials,
    });
    if (!rep.ok) throw await this.ParseError(rep);

    const rs = await rep.text();
    try {
      return JSON.parse(rs) as T;
    } catch (e) {
      return rs as unknown as T;
    }
  }

  iotbrlabsCtrlController = {
    count: (search: { where?: void }) => {
      return this.Fetch<loopback_Count>("get", "/clientes/count", { search });
    },

    findById: (
      id: number,
      search: {
        filter?: void;
      },
    ) => {
      return this.Fetch<ClientesWithRelations>("get", `/clientes/${id}`, {
        search,
      });
    },

    replaceById: (id: number, body: Clientes) => {
      return this.Fetch<unknown>("put", `/clientes/${id}`, { body });
    },

    updateById: (id: number, body: ClientesPartial) => {
      return this.Fetch<unknown>("patch", `/clientes/${id}`, { body });
    },

    deleteById: (id: number) => {
      return this.Fetch<unknown>("delete", `/clientes/${id}`, {});
    },

    find: (search: { filter?: void }) => {
      return this.Fetch<ClientesWithRelations[]>("get", "/clientes", {
        search,
      });
    },

    create: (body: NewClientes) => {
      return this.Fetch<Clientes>("post", "/clientes", { body });
    },

    updateAll: (
      body: ClientesPartial,
      search: {
        where?: void;
      },
    ) => {
      return this.Fetch<loopback_Count>("patch", "/clientes", { search, body });
    },
  };

  pingController = {
    ping: () => {
      return this.Fetch<PingResponse>("get", "/ping", {});
    },
  };
}

export type Clientes = {
  id?: number;
  wallet?: string | null;
  identificador?: string | null;
  tipocliente?: number | null;
};

export type Clientes_Filter = {
  offset?: number;
  limit?: number;
  skip?: number;
  order?: string | string[];
  fields?:
    | {
        id?: boolean;
        wallet?: boolean;
        identificador?: boolean;
        tipocliente?: boolean;
      }
    | ("id" | "wallet" | "identificador" | "tipocliente")[];
};

export type Clientes_Filter1 = {
  offset?: number;
  limit?: number;
  skip?: number;
  order?: string | string[];
  where?: object;
  fields?:
    | {
        id?: boolean;
        wallet?: boolean;
        identificador?: boolean;
        tipocliente?: boolean;
      }
    | ("id" | "wallet" | "identificador" | "tipocliente")[];
};

export type ClientesPartial = {
  id?: number;
  wallet?: string | null;
  identificador?: string | null;
  tipocliente?: number | null;
};

export type ClientesWithRelations = {
  id?: number;
  wallet?: string | null;
  identificador?: string | null;
  tipocliente?: number | null;
};

export type NewClientes = {
  wallet?: string | null;
  identificador?: string | null;
  tipocliente?: number | null;
};

export type PingResponse = {
  greeting?: string;
  date?: string;
  url?: string;
  headers?: {
    "Content-Type"?: string;
  };
};

export type loopback_Count = {
  count?: number;
};
