/* tslint:disable */
/* eslint-disable */
/**
 * iotbrlabs-api
 * API da iotbrlabs
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: mhd_look@hotmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface Clientes
 */
export interface Clientes {
    /**
     * 
     * @type {number}
     * @memberof Clientes
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Clientes
     */
    'wallet'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Clientes
     */
    'identificador'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Clientes
     */
    'tipocliente'?: number | null;
}
/**
 * @type ClientesFields
 * @export
 */
export type ClientesFields = ClientesFieldsOneOf | Set<string>;

/**
 * 
 * @export
 * @interface ClientesFieldsOneOf
 */
export interface ClientesFieldsOneOf {
    /**
     * 
     * @type {boolean}
     * @memberof ClientesFieldsOneOf
     */
    'id'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ClientesFieldsOneOf
     */
    'wallet'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ClientesFieldsOneOf
     */
    'identificador'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ClientesFieldsOneOf
     */
    'tipocliente'?: boolean;
}
/**
 * 
 * @export
 * @interface ClientesFilter
 */
export interface ClientesFilter {
    /**
     * 
     * @type {number}
     * @memberof ClientesFilter
     */
    'offset'?: number;
    /**
     * 
     * @type {number}
     * @memberof ClientesFilter
     */
    'limit'?: number;
    /**
     * 
     * @type {number}
     * @memberof ClientesFilter
     */
    'skip'?: number;
    /**
     * 
     * @type {ClientesFilterOrder}
     * @memberof ClientesFilter
     */
    'order'?: ClientesFilterOrder;
    /**
     * 
     * @type {ClientesFields}
     * @memberof ClientesFilter
     */
    'fields'?: ClientesFields;
}
/**
 * 
 * @export
 * @interface ClientesFilter1
 */
export interface ClientesFilter1 {
    /**
     * 
     * @type {number}
     * @memberof ClientesFilter1
     */
    'offset'?: number;
    /**
     * 
     * @type {number}
     * @memberof ClientesFilter1
     */
    'limit'?: number;
    /**
     * 
     * @type {number}
     * @memberof ClientesFilter1
     */
    'skip'?: number;
    /**
     * 
     * @type {ClientesFilterOrder}
     * @memberof ClientesFilter1
     */
    'order'?: ClientesFilterOrder;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ClientesFilter1
     */
    'where'?: { [key: string]: any; };
    /**
     * 
     * @type {ClientesFields}
     * @memberof ClientesFilter1
     */
    'fields'?: ClientesFields;
}
/**
 * @type ClientesFilterOrder
 * @export
 */
export type ClientesFilterOrder = Array<string> | string;

/**
 * (tsType: Partial<Clientes>, schemaOptions: { partial: true })
 * @export
 * @interface ClientesPartial
 */
export interface ClientesPartial {
    /**
     * 
     * @type {number}
     * @memberof ClientesPartial
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ClientesPartial
     */
    'wallet'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ClientesPartial
     */
    'identificador'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ClientesPartial
     */
    'tipocliente'?: number | null;
}
/**
 * (tsType: ClientesWithRelations, schemaOptions: { includeRelations: true })
 * @export
 * @interface ClientesWithRelations
 */
export interface ClientesWithRelations {
    /**
     * 
     * @type {number}
     * @memberof ClientesWithRelations
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ClientesWithRelations
     */
    'wallet'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ClientesWithRelations
     */
    'identificador'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ClientesWithRelations
     */
    'tipocliente'?: number | null;
}
/**
 * 
 * @export
 * @interface LoopbackCount
 */
export interface LoopbackCount {
    /**
     * 
     * @type {number}
     * @memberof LoopbackCount
     */
    'count'?: number;
}
/**
 * (tsType: Omit<Clientes, \'id\'>, schemaOptions: { title: \'NewClientes\', exclude: [ \'id\' ] })
 * @export
 * @interface NewClientes
 */
export interface NewClientes {
    /**
     * 
     * @type {string}
     * @memberof NewClientes
     */
    'wallet'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NewClientes
     */
    'identificador'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof NewClientes
     */
    'tipocliente'?: number | null;
}
/**
 * 
 * @export
 * @interface PingResponse
 */
export interface PingResponse {
    /**
     * 
     * @type {string}
     * @memberof PingResponse
     */
    'greeting'?: string;
    /**
     * 
     * @type {string}
     * @memberof PingResponse
     */
    'date'?: string;
    /**
     * 
     * @type {string}
     * @memberof PingResponse
     */
    'url'?: string;
    /**
     * 
     * @type {PingResponseHeaders}
     * @memberof PingResponse
     */
    'headers'?: PingResponseHeaders;
}
/**
 * 
 * @export
 * @interface PingResponseHeaders
 */
export interface PingResponseHeaders {
    [key: string]: any;

    /**
     * 
     * @type {string}
     * @memberof PingResponseHeaders
     */
    'Content-Type'?: string;
}

/**
 * IotbrlabsCtrlControllerApi - axios parameter creator
 * @export
 */
export const IotbrlabsCtrlControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {{ [key: string]: any; }} [where] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iotbrlabsCtrlControllerCount: async (where?: { [key: string]: any; }, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/clientes/count`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (where !== undefined) {
                localVarQueryParameter['where'] = where;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {NewClientes} [newClientes] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iotbrlabsCtrlControllerCreate: async (newClientes?: NewClientes, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/clientes`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(newClientes, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iotbrlabsCtrlControllerDeleteById: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('iotbrlabsCtrlControllerDeleteById', 'id', id)
            const localVarPath = `/clientes/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {ClientesFilter1} [filter] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iotbrlabsCtrlControllerFind: async (filter?: ClientesFilter1, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/clientes`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (filter !== undefined) {
                localVarQueryParameter['filter'] = filter;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {ClientesFilter} [filter] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iotbrlabsCtrlControllerFindById: async (id: number, filter?: ClientesFilter, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('iotbrlabsCtrlControllerFindById', 'id', id)
            const localVarPath = `/clientes/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (filter !== undefined) {
                localVarQueryParameter['filter'] = filter;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {Clientes} [clientes] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iotbrlabsCtrlControllerReplaceById: async (id: number, clientes?: Clientes, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('iotbrlabsCtrlControllerReplaceById', 'id', id)
            const localVarPath = `/clientes/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(clientes, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {{ [key: string]: any; }} [where] 
         * @param {ClientesPartial} [clientesPartial] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iotbrlabsCtrlControllerUpdateAll: async (where?: { [key: string]: any; }, clientesPartial?: ClientesPartial, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/clientes`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (where !== undefined) {
                localVarQueryParameter['where'] = where;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(clientesPartial, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {ClientesPartial} [clientesPartial] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iotbrlabsCtrlControllerUpdateById: async (id: number, clientesPartial?: ClientesPartial, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('iotbrlabsCtrlControllerUpdateById', 'id', id)
            const localVarPath = `/clientes/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(clientesPartial, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * IotbrlabsCtrlControllerApi - functional programming interface
 * @export
 */
export const IotbrlabsCtrlControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = IotbrlabsCtrlControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {{ [key: string]: any; }} [where] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iotbrlabsCtrlControllerCount(where?: { [key: string]: any; }, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LoopbackCount>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iotbrlabsCtrlControllerCount(where, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IotbrlabsCtrlControllerApi.iotbrlabsCtrlControllerCount']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {NewClientes} [newClientes] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iotbrlabsCtrlControllerCreate(newClientes?: NewClientes, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Clientes>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iotbrlabsCtrlControllerCreate(newClientes, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IotbrlabsCtrlControllerApi.iotbrlabsCtrlControllerCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iotbrlabsCtrlControllerDeleteById(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iotbrlabsCtrlControllerDeleteById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IotbrlabsCtrlControllerApi.iotbrlabsCtrlControllerDeleteById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {ClientesFilter1} [filter] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iotbrlabsCtrlControllerFind(filter?: ClientesFilter1, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ClientesWithRelations>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iotbrlabsCtrlControllerFind(filter, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IotbrlabsCtrlControllerApi.iotbrlabsCtrlControllerFind']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {ClientesFilter} [filter] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iotbrlabsCtrlControllerFindById(id: number, filter?: ClientesFilter, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ClientesWithRelations>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iotbrlabsCtrlControllerFindById(id, filter, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IotbrlabsCtrlControllerApi.iotbrlabsCtrlControllerFindById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {Clientes} [clientes] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iotbrlabsCtrlControllerReplaceById(id: number, clientes?: Clientes, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iotbrlabsCtrlControllerReplaceById(id, clientes, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IotbrlabsCtrlControllerApi.iotbrlabsCtrlControllerReplaceById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {{ [key: string]: any; }} [where] 
         * @param {ClientesPartial} [clientesPartial] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iotbrlabsCtrlControllerUpdateAll(where?: { [key: string]: any; }, clientesPartial?: ClientesPartial, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LoopbackCount>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iotbrlabsCtrlControllerUpdateAll(where, clientesPartial, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IotbrlabsCtrlControllerApi.iotbrlabsCtrlControllerUpdateAll']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {ClientesPartial} [clientesPartial] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iotbrlabsCtrlControllerUpdateById(id: number, clientesPartial?: ClientesPartial, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iotbrlabsCtrlControllerUpdateById(id, clientesPartial, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IotbrlabsCtrlControllerApi.iotbrlabsCtrlControllerUpdateById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * IotbrlabsCtrlControllerApi - factory interface
 * @export
 */
export const IotbrlabsCtrlControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = IotbrlabsCtrlControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {{ [key: string]: any; }} [where] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iotbrlabsCtrlControllerCount(where?: { [key: string]: any; }, options?: RawAxiosRequestConfig): AxiosPromise<LoopbackCount> {
            return localVarFp.iotbrlabsCtrlControllerCount(where, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {NewClientes} [newClientes] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iotbrlabsCtrlControllerCreate(newClientes?: NewClientes, options?: RawAxiosRequestConfig): AxiosPromise<Clientes> {
            return localVarFp.iotbrlabsCtrlControllerCreate(newClientes, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iotbrlabsCtrlControllerDeleteById(id: number, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.iotbrlabsCtrlControllerDeleteById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ClientesFilter1} [filter] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iotbrlabsCtrlControllerFind(filter?: ClientesFilter1, options?: RawAxiosRequestConfig): AxiosPromise<Array<ClientesWithRelations>> {
            return localVarFp.iotbrlabsCtrlControllerFind(filter, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id 
         * @param {ClientesFilter} [filter] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iotbrlabsCtrlControllerFindById(id: number, filter?: ClientesFilter, options?: RawAxiosRequestConfig): AxiosPromise<ClientesWithRelations> {
            return localVarFp.iotbrlabsCtrlControllerFindById(id, filter, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id 
         * @param {Clientes} [clientes] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iotbrlabsCtrlControllerReplaceById(id: number, clientes?: Clientes, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.iotbrlabsCtrlControllerReplaceById(id, clientes, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {{ [key: string]: any; }} [where] 
         * @param {ClientesPartial} [clientesPartial] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iotbrlabsCtrlControllerUpdateAll(where?: { [key: string]: any; }, clientesPartial?: ClientesPartial, options?: RawAxiosRequestConfig): AxiosPromise<LoopbackCount> {
            return localVarFp.iotbrlabsCtrlControllerUpdateAll(where, clientesPartial, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id 
         * @param {ClientesPartial} [clientesPartial] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iotbrlabsCtrlControllerUpdateById(id: number, clientesPartial?: ClientesPartial, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.iotbrlabsCtrlControllerUpdateById(id, clientesPartial, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * IotbrlabsCtrlControllerApi - object-oriented interface
 * @export
 * @class IotbrlabsCtrlControllerApi
 * @extends {BaseAPI}
 */
export class IotbrlabsCtrlControllerApi extends BaseAPI {
    /**
     * 
     * @param {{ [key: string]: any; }} [where] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IotbrlabsCtrlControllerApi
     */
    public iotbrlabsCtrlControllerCount(where?: { [key: string]: any; }, options?: RawAxiosRequestConfig) {
        return IotbrlabsCtrlControllerApiFp(this.configuration).iotbrlabsCtrlControllerCount(where, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {NewClientes} [newClientes] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IotbrlabsCtrlControllerApi
     */
    public iotbrlabsCtrlControllerCreate(newClientes?: NewClientes, options?: RawAxiosRequestConfig) {
        return IotbrlabsCtrlControllerApiFp(this.configuration).iotbrlabsCtrlControllerCreate(newClientes, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IotbrlabsCtrlControllerApi
     */
    public iotbrlabsCtrlControllerDeleteById(id: number, options?: RawAxiosRequestConfig) {
        return IotbrlabsCtrlControllerApiFp(this.configuration).iotbrlabsCtrlControllerDeleteById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ClientesFilter1} [filter] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IotbrlabsCtrlControllerApi
     */
    public iotbrlabsCtrlControllerFind(filter?: ClientesFilter1, options?: RawAxiosRequestConfig) {
        return IotbrlabsCtrlControllerApiFp(this.configuration).iotbrlabsCtrlControllerFind(filter, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} id 
     * @param {ClientesFilter} [filter] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IotbrlabsCtrlControllerApi
     */
    public iotbrlabsCtrlControllerFindById(id: number, filter?: ClientesFilter, options?: RawAxiosRequestConfig) {
        return IotbrlabsCtrlControllerApiFp(this.configuration).iotbrlabsCtrlControllerFindById(id, filter, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} id 
     * @param {Clientes} [clientes] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IotbrlabsCtrlControllerApi
     */
    public iotbrlabsCtrlControllerReplaceById(id: number, clientes?: Clientes, options?: RawAxiosRequestConfig) {
        return IotbrlabsCtrlControllerApiFp(this.configuration).iotbrlabsCtrlControllerReplaceById(id, clientes, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {{ [key: string]: any; }} [where] 
     * @param {ClientesPartial} [clientesPartial] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IotbrlabsCtrlControllerApi
     */
    public iotbrlabsCtrlControllerUpdateAll(where?: { [key: string]: any; }, clientesPartial?: ClientesPartial, options?: RawAxiosRequestConfig) {
        return IotbrlabsCtrlControllerApiFp(this.configuration).iotbrlabsCtrlControllerUpdateAll(where, clientesPartial, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} id 
     * @param {ClientesPartial} [clientesPartial] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IotbrlabsCtrlControllerApi
     */
    public iotbrlabsCtrlControllerUpdateById(id: number, clientesPartial?: ClientesPartial, options?: RawAxiosRequestConfig) {
        return IotbrlabsCtrlControllerApiFp(this.configuration).iotbrlabsCtrlControllerUpdateById(id, clientesPartial, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * PingControllerApi - axios parameter creator
 * @export
 */
export const PingControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pingControllerPing: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/ping`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PingControllerApi - functional programming interface
 * @export
 */
export const PingControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PingControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async pingControllerPing(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PingResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.pingControllerPing(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PingControllerApi.pingControllerPing']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PingControllerApi - factory interface
 * @export
 */
export const PingControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PingControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pingControllerPing(options?: RawAxiosRequestConfig): AxiosPromise<PingResponse> {
            return localVarFp.pingControllerPing(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PingControllerApi - object-oriented interface
 * @export
 * @class PingControllerApi
 * @extends {BaseAPI}
 */
export class PingControllerApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PingControllerApi
     */
    public pingControllerPing(options?: RawAxiosRequestConfig) {
        return PingControllerApiFp(this.configuration).pingControllerPing(options).then((request) => request(this.axios, this.basePath));
    }
}



