/* tslint:disable */
/* eslint-disable */
/**
 * iotbrlabs-api
 * API da iotbrlabs
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: mhd_look@hotmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClientesFieldsOneOf
 */
export interface ClientesFieldsOneOf {
    /**
     * 
     * @type {boolean}
     * @memberof ClientesFieldsOneOf
     */
    id?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ClientesFieldsOneOf
     */
    wallet?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ClientesFieldsOneOf
     */
    identificador?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ClientesFieldsOneOf
     */
    tipocliente?: boolean;
}

/**
 * Check if a given object implements the ClientesFieldsOneOf interface.
 */
export function instanceOfClientesFieldsOneOf(value: object): value is ClientesFieldsOneOf {
    return true;
}

export function ClientesFieldsOneOfFromJSON(json: any): ClientesFieldsOneOf {
    return ClientesFieldsOneOfFromJSONTyped(json, false);
}

export function ClientesFieldsOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientesFieldsOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'wallet': json['wallet'] == null ? undefined : json['wallet'],
        'identificador': json['identificador'] == null ? undefined : json['identificador'],
        'tipocliente': json['tipocliente'] == null ? undefined : json['tipocliente'],
    };
}

  export function ClientesFieldsOneOfToJSON(json: any): ClientesFieldsOneOf {
      return ClientesFieldsOneOfToJSONTyped(json, false);
  }

  export function ClientesFieldsOneOfToJSONTyped(value?: ClientesFieldsOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'wallet': value['wallet'],
        'identificador': value['identificador'],
        'tipocliente': value['tipocliente'],
    };
}

