/* tslint:disable */
/* eslint-disable */
/**
 * iotbrlabs-api
 * API da iotbrlabs
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: mhd_look@hotmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ClientesFilterOrder } from './ClientesFilterOrder';
import {
    ClientesFilterOrderFromJSON,
    ClientesFilterOrderFromJSONTyped,
    ClientesFilterOrderToJSON,
    ClientesFilterOrderToJSONTyped,
} from './ClientesFilterOrder';
import type { ClientesFields } from './ClientesFields';
import {
    ClientesFieldsFromJSON,
    ClientesFieldsFromJSONTyped,
    ClientesFieldsToJSON,
    ClientesFieldsToJSONTyped,
} from './ClientesFields';

/**
 * 
 * @export
 * @interface ClientesFilter
 */
export interface ClientesFilter {
    /**
     * 
     * @type {number}
     * @memberof ClientesFilter
     */
    offset?: number;
    /**
     * 
     * @type {number}
     * @memberof ClientesFilter
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof ClientesFilter
     */
    skip?: number;
    /**
     * 
     * @type {ClientesFilterOrder}
     * @memberof ClientesFilter
     */
    order?: ClientesFilterOrder;
    /**
     * 
     * @type {ClientesFields}
     * @memberof ClientesFilter
     */
    fields?: ClientesFields;
}

/**
 * Check if a given object implements the ClientesFilter interface.
 */
export function instanceOfClientesFilter(value: object): value is ClientesFilter {
    return true;
}

export function ClientesFilterFromJSON(json: any): ClientesFilter {
    return ClientesFilterFromJSONTyped(json, false);
}

export function ClientesFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientesFilter {
    if (json == null) {
        return json;
    }
    return {
        
        'offset': json['offset'] == null ? undefined : json['offset'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'skip': json['skip'] == null ? undefined : json['skip'],
        'order': json['order'] == null ? undefined : ClientesFilterOrderFromJSON(json['order']),
        'fields': json['fields'] == null ? undefined : ClientesFieldsFromJSON(json['fields']),
    };
}

  export function ClientesFilterToJSON(json: any): ClientesFilter {
      return ClientesFilterToJSONTyped(json, false);
  }

  export function ClientesFilterToJSONTyped(value?: ClientesFilter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'offset': value['offset'],
        'limit': value['limit'],
        'skip': value['skip'],
        'order': ClientesFilterOrderToJSON(value['order']),
        'fields': ClientesFieldsToJSON(value['fields']),
    };
}

