/* tslint:disable */
/* eslint-disable */
/**
 * iotbrlabs-api
 * API da iotbrlabs
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: mhd_look@hotmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * (tsType: ClientesWithRelations, schemaOptions: { includeRelations: true })
 * @export
 * @interface ClientesWithRelations
 */
export interface ClientesWithRelations {
    /**
     * 
     * @type {number}
     * @memberof ClientesWithRelations
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof ClientesWithRelations
     */
    wallet?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ClientesWithRelations
     */
    identificador?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ClientesWithRelations
     */
    tipocliente?: number | null;
}

/**
 * Check if a given object implements the ClientesWithRelations interface.
 */
export function instanceOfClientesWithRelations(value: object): value is ClientesWithRelations {
    return true;
}

export function ClientesWithRelationsFromJSON(json: any): ClientesWithRelations {
    return ClientesWithRelationsFromJSONTyped(json, false);
}

export function ClientesWithRelationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientesWithRelations {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'wallet': json['wallet'] == null ? undefined : json['wallet'],
        'identificador': json['identificador'] == null ? undefined : json['identificador'],
        'tipocliente': json['tipocliente'] == null ? undefined : json['tipocliente'],
    };
}

  export function ClientesWithRelationsToJSON(json: any): ClientesWithRelations {
      return ClientesWithRelationsToJSONTyped(json, false);
  }

  export function ClientesWithRelationsToJSONTyped(value?: Omit<ClientesWithRelations, 'id'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'wallet': value['wallet'],
        'identificador': value['identificador'],
        'tipocliente': value['tipocliente'],
    };
}

