/* tslint:disable */
/* eslint-disable */
/**
 * iotbrlabs-api
 * API da iotbrlabs
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: mhd_look@hotmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * (tsType: Partial<Clientes>, schemaOptions: { partial: true })
 * @export
 * @interface ClientesPartial
 */
export interface ClientesPartial {
    /**
     * 
     * @type {number}
     * @memberof ClientesPartial
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof ClientesPartial
     */
    wallet?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ClientesPartial
     */
    identificador?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ClientesPartial
     */
    tipocliente?: number | null;
}

/**
 * Check if a given object implements the ClientesPartial interface.
 */
export function instanceOfClientesPartial(value: object): value is ClientesPartial {
    return true;
}

export function ClientesPartialFromJSON(json: any): ClientesPartial {
    return ClientesPartialFromJSONTyped(json, false);
}

export function ClientesPartialFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientesPartial {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'wallet': json['wallet'] == null ? undefined : json['wallet'],
        'identificador': json['identificador'] == null ? undefined : json['identificador'],
        'tipocliente': json['tipocliente'] == null ? undefined : json['tipocliente'],
    };
}

  export function ClientesPartialToJSON(json: any): ClientesPartial {
      return ClientesPartialToJSONTyped(json, false);
  }

  export function ClientesPartialToJSONTyped(value?: Omit<ClientesPartial, 'id'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'wallet': value['wallet'],
        'identificador': value['identificador'],
        'tipocliente': value['tipocliente'],
    };
}

