/* tslint:disable */
/* eslint-disable */
/**
 * iotbrlabs-api
 * API da iotbrlabs
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: mhd_look@hotmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Clientes
 */
export interface Clientes {
    /**
     * 
     * @type {number}
     * @memberof Clientes
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof Clientes
     */
    wallet?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Clientes
     */
    identificador?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Clientes
     */
    tipocliente?: number | null;
}

/**
 * Check if a given object implements the Clientes interface.
 */
export function instanceOfClientes(value: object): value is Clientes {
    return true;
}

export function ClientesFromJSON(json: any): Clientes {
    return ClientesFromJSONTyped(json, false);
}

export function ClientesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Clientes {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'wallet': json['wallet'] == null ? undefined : json['wallet'],
        'identificador': json['identificador'] == null ? undefined : json['identificador'],
        'tipocliente': json['tipocliente'] == null ? undefined : json['tipocliente'],
    };
}

  export function ClientesToJSON(json: any): Clientes {
      return ClientesToJSONTyped(json, false);
  }

  export function ClientesToJSONTyped(value?: Omit<Clientes, 'id'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'wallet': value['wallet'],
        'identificador': value['identificador'],
        'tipocliente': value['tipocliente'],
    };
}

