/* tslint:disable */
/* eslint-disable */
/**
 * iotbrlabs-api
 * API da iotbrlabs
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: mhd_look@hotmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ClientesFieldsOneOf } from './ClientesFieldsOneOf';
import {
    instanceOfClientesFieldsOneOf,
    ClientesFieldsOneOfFromJSON,
    ClientesFieldsOneOfFromJSONTyped,
    ClientesFieldsOneOfToJSON,
} from './ClientesFieldsOneOf';
import type { Set<string> } from './Set&lt;string&gt;';
import {
    instanceOfSet<string>,
    Set<string>FromJSON,
    Set<string>FromJSONTyped,
    Set<string>ToJSON,
} from './Set&lt;string&gt;';

/**
 * @type ClientesFields
 * 
 * @export
 */
export type ClientesFields = ClientesFieldsOneOf | Set<string>;

export function ClientesFieldsFromJSON(json: any): ClientesFields {
    return ClientesFieldsFromJSONTyped(json, false);
}

export function ClientesFieldsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientesFields {
    if (json == null) {
        return json;
    }
    if (instanceOfClientesFieldsOneOf(json)) {
        return ClientesFieldsOneOfFromJSONTyped(json, true);
    }
    if (instanceOfSet<string>(json)) {
        return Set<string>FromJSONTyped(json, true);
    }

    return {} as any;
}

export function ClientesFieldsToJSON(value?: ClientesFields | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfClientesFieldsOneOf(value)) {
        return ClientesFieldsOneOfToJSON(value as ClientesFieldsOneOf);
    }
    if (instanceOfSet<string>(value)) {
        return Set<string>ToJSON(value as Set<string>);
    }

    return {};
}

