/* tslint:disable */
/* eslint-disable */
/**
 * iotbrlabs-api
 * API da iotbrlabs
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: mhd_look@hotmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type ClientesFilterOrder
 * 
 * @export
 */
export type ClientesFilterOrder = Array<string> | string;

export function ClientesFilterOrderFromJSON(json: any): ClientesFilterOrder {
    return ClientesFilterOrderFromJSONTyped(json, false);
}

export function ClientesFilterOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientesFilterOrder {
    if (json == null) {
        return json;
    }
    if (instanceOfArray<string>(json)) {
        return Array<string>FromJSONTyped(json, true);
    }
    if (instanceOfstring(json)) {
        return stringFromJSONTyped(json, true);
    }

    return {} as any;
}

export function ClientesFilterOrderToJSON(value?: ClientesFilterOrder | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfArray<string>(value)) {
        return Array<string>ToJSON(value as Array<string>);
    }
    if (instanceOfstring(value)) {
        return stringToJSON(value as string);
    }

    return {};
}

