/* tslint:disable */
/* eslint-disable */
/**
 * iotbrlabs-api
 * API da iotbrlabs
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: mhd_look@hotmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoopbackCount
 */
export interface LoopbackCount {
    /**
     * 
     * @type {number}
     * @memberof LoopbackCount
     */
    count?: number;
}

/**
 * Check if a given object implements the LoopbackCount interface.
 */
export function instanceOfLoopbackCount(value: object): value is LoopbackCount {
    return true;
}

export function LoopbackCountFromJSON(json: any): LoopbackCount {
    return LoopbackCountFromJSONTyped(json, false);
}

export function LoopbackCountFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoopbackCount {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
    };
}

  export function LoopbackCountToJSON(json: any): LoopbackCount {
      return LoopbackCountToJSONTyped(json, false);
  }

  export function LoopbackCountToJSONTyped(value?: LoopbackCount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
    };
}

