/* tslint:disable */
/* eslint-disable */
/**
 * iotbrlabs-api
 * API da iotbrlabs
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: mhd_look@hotmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * (tsType: Omit<Clientes, 'id'>, schemaOptions: { title: 'NewClientes', exclude: [ 'id' ] })
 * @export
 * @interface NewClientes
 */
export interface NewClientes {
    /**
     * 
     * @type {string}
     * @memberof NewClientes
     */
    wallet?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NewClientes
     */
    identificador?: string | null;
    /**
     * 
     * @type {number}
     * @memberof NewClientes
     */
    tipocliente?: number | null;
}

/**
 * Check if a given object implements the NewClientes interface.
 */
export function instanceOfNewClientes(value: object): value is NewClientes {
    return true;
}

export function NewClientesFromJSON(json: any): NewClientes {
    return NewClientesFromJSONTyped(json, false);
}

export function NewClientesFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewClientes {
    if (json == null) {
        return json;
    }
    return {
        
        'wallet': json['wallet'] == null ? undefined : json['wallet'],
        'identificador': json['identificador'] == null ? undefined : json['identificador'],
        'tipocliente': json['tipocliente'] == null ? undefined : json['tipocliente'],
    };
}

  export function NewClientesToJSON(json: any): NewClientes {
      return NewClientesToJSONTyped(json, false);
  }

  export function NewClientesToJSONTyped(value?: NewClientes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'wallet': value['wallet'],
        'identificador': value['identificador'],
        'tipocliente': value['tipocliente'],
    };
}

