/* tslint:disable */
/* eslint-disable */
/**
 * iotbrlabs-api
 * API da iotbrlabs
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: mhd_look@hotmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PingResponseHeaders
 */
export interface PingResponseHeaders {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof PingResponseHeaders
     */
    contentType?: string;
}

/**
 * Check if a given object implements the PingResponseHeaders interface.
 */
export function instanceOfPingResponseHeaders(value: object): value is PingResponseHeaders {
    return true;
}

export function PingResponseHeadersFromJSON(json: any): PingResponseHeaders {
    return PingResponseHeadersFromJSONTyped(json, false);
}

export function PingResponseHeadersFromJSONTyped(json: any, ignoreDiscriminator: boolean): PingResponseHeaders {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'contentType': json['Content-Type'] == null ? undefined : json['Content-Type'],
    };
}

  export function PingResponseHeadersToJSON(json: any): PingResponseHeaders {
      return PingResponseHeadersToJSONTyped(json, false);
  }

  export function PingResponseHeadersToJSONTyped(value?: PingResponseHeaders | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'Content-Type': value['contentType'],
    };
}

