/* tslint:disable */
/* eslint-disable */
/**
 * iotbrlabs-api
 * API da iotbrlabs
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: mhd_look@hotmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PingResponseHeaders } from './PingResponseHeaders';
import {
    PingResponseHeadersFromJSON,
    PingResponseHeadersFromJSONTyped,
    PingResponseHeadersToJSON,
    PingResponseHeadersToJSONTyped,
} from './PingResponseHeaders';

/**
 * 
 * @export
 * @interface PingResponse
 */
export interface PingResponse {
    /**
     * 
     * @type {string}
     * @memberof PingResponse
     */
    greeting?: string;
    /**
     * 
     * @type {string}
     * @memberof PingResponse
     */
    date?: string;
    /**
     * 
     * @type {string}
     * @memberof PingResponse
     */
    url?: string;
    /**
     * 
     * @type {PingResponseHeaders}
     * @memberof PingResponse
     */
    headers?: PingResponseHeaders;
}

/**
 * Check if a given object implements the PingResponse interface.
 */
export function instanceOfPingResponse(value: object): value is PingResponse {
    return true;
}

export function PingResponseFromJSON(json: any): PingResponse {
    return PingResponseFromJSONTyped(json, false);
}

export function PingResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PingResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'greeting': json['greeting'] == null ? undefined : json['greeting'],
        'date': json['date'] == null ? undefined : json['date'],
        'url': json['url'] == null ? undefined : json['url'],
        'headers': json['headers'] == null ? undefined : PingResponseHeadersFromJSON(json['headers']),
    };
}

  export function PingResponseToJSON(json: any): PingResponse {
      return PingResponseToJSONTyped(json, false);
  }

  export function PingResponseToJSONTyped(value?: PingResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'greeting': value['greeting'],
        'date': value['date'],
        'url': value['url'],
        'headers': PingResponseHeadersToJSON(value['headers']),
    };
}

